version: "2.1"
volumes:
    speedtest-data:
    settings:
    dashboard-data:
services:
  finternet:
    build: ./finternet
    network_mode: host
    privileged: true
    restart: always
  speedtest:
    build: ./speedtest
    privileged: true
    restart: never
    volumes:
      - 'speedtest-data:/data'
    network_mode: host
  connector:
    image:  balenablocks/connector
    restart: always
    labels:
      io.balena.features.balena-api: '1'
    privileged: true
  dashboard:
    restart: always
    build: ./dashboard
    ports:
      - "80"
    volumes:
        - 'dashboard-data:/data'
  influxdb:
    image: influxdb@sha256:73f876e0c3bd02900f829d4884f53fdfffd7098dd572406ba549eed955bf821f
    container_name: influxdb
    restart: always
    environment:
      - INFLUXDB_DB=balena
      - INFLUXDB_USER=balena
      - INFLUXDB_ADMIN_ENABLED=true
      - INFLUXDB_ADMIN_USER=admin
      - INFLUXDB_ADMIN_PASSWORD=admin
      - INFLUXDB_DATA_DIR=/data
    volumes:
      - 'speedtest-data:/data'
  mqtt:
    image: arm32v6/eclipse-mosquitto@sha256:ec3e1dbb9e198ff04d62c2d0f6eff74cad7438c7d080b89a28428fb96c8479c4
    ports:
      - "1883:1883"
    restart: always

